apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app1: web1
  template:
    metadata:
      labels:
        app1: web1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
